version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:REGION:ACCOUNT_ID:task-definition/ECS_SERVICE_NAME"
        LoadBalancerInfo:
          ContainerName: "SERVICE_NAME"
          ContainerPort: CONTAINER_PORT
        CapacityProviderStrategy:
          - Base: 1
            CapacityProvider: "CAPACITY_PROVIDER_NAME"
            Weight: 1