version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:*REGION*:*ACCOUNT_ID:task-definition/*SERVICE_NAME*:latest"
        LoadBalancerInfo:
          ContainerName: "*SERVICE_NAME*"
          ContainerPort: *CONTAINER_PORT*